In [ ]:
import numpy as np
print(np.__version__)

1.23.5


In [ ]:
# Question : Create a 3×3 numpy array of all True’s



array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
# Question : Extract all odd numbers from array (sample given below)
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([1, 3, 5, 7, 9])



array([1, 3, 5, 7, 9])

In [ ]:
# Question: Replace all odd numbers in an array with -1
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
#(below given is a sample only)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
# Question: Replace all odd numbers in arr with -1 without changing arr
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: out
# array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])




Modified Array

Original Array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Question: Convert a 1D array to a 2D array with 2 rows
# input: np.arange(10)
# output array([[0, 1, 2, 3, 4],
#               [5, 6, 7, 8, 9]])



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
# Question: Stack arrays a and b vertically
# input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)

# output: array([[0, 1, 2, 3, 4],
#                [5, 6, 7, 8, 9],
#                [1, 1, 1, 1, 1],
#                [1, 1, 1, 1, 1]])



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
# Question: Stack the arrays a and b horizontally.

# Input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)
# Output: array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#                [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])



array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [ ]:
# Question: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
# Question: Get the common items between a and b

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: array([2, 4])


array([2, 4])

In [ ]:
# Question: From array a remove all items present in array b

# Input: a = np.array([1,2,3,4,5])
#        b = np.array([5,6,7,8,9])

# Output: array([1,2,3,4])


array([1, 2, 3, 4])

In [ ]:
# Question: Get the positions where elements of a and b match

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: (array([1, 3, 5, 7]),)


(array([1, 3, 5, 7]),)

In [ ]:
# Question: Get all items between 5 and 10 from a.

# Input: a = np.array([2, 6, 1, 9, 10, 3, 27])
# Output: (array([6, 9, 10]),)



array([ 6,  9, 10])

In [ ]:
# Question: Swap columns 1 and 2 in the array arr.


In [ ]:
# Question: Swap rows 1 and 2 in the array arr:



In [ ]:
# Question: Reverse the rows of a 2D array arr.


Original array
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [ ]:
# Question: Reverse the columns of a 2D array arr.


Original array
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [ ]:
# Question: Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.



array([[5.03087299, 8.39575121, 6.0274367 ],
       [6.99159616, 9.28619573, 5.42767904],
       [6.76674286, 8.79660633, 5.71677688],
       [5.7184694 , 6.66369604, 7.73447946],
       [6.62111094, 8.52473757, 5.54982207]])

In [ ]:
# Question: Print or show only 3 decimal places of the numpy array rand_arr.


array([[0.424, 0.919, 0.455],
       [0.782, 0.715, 0.108],
       [0.536, 0.986, 0.853],
       [0.577, 0.738, 0.069],
       [0.562, 0.524, 0.234]])

In [ ]:
# Question: Print the full numpy array (large array) a without truncating.



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# Question: Import the iris dataset keeping the text intact.
#(Iris.csv is given)

In [ ]:
# Question: Extract the text column species from the 1D iris imported in previous question.


array([b'1', b'2', b'3', ..., b'148', b'149', b'150'], dtype=object)

In [ ]:
# Question: Convert the 1D iris to 2D array iris_2d by omitting the species text field.


array([[  1. ,   5.1,   3.5,   1.4],
       [  2. ,   4.9,   3. ,   1.4],
       [  3. ,   4.7,   3.2,   1.3],
       ...,
       [148. ,   6.5,   3. ,   5.2],
       [149. ,   6.2,   3.4,   5.4],
       [150. ,   5.9,   3. ,   5.1]])

In [ ]:
# Question: Find the mean, median, standard deviation of iris's sepallength (1st column)



Mean 5.843333333333334
Median 5.8
Standard Deviation 0.8253012917851409


In [ ]:
# Question: Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.



array([0.222, 0.167, 0.111, ..., 0.611, 0.528, 0.444])

In [ ]:
# Question: Compute the softmax score of sepallength.


array([0.002, 0.002, 0.001, ..., 0.009, 0.007, 0.005])

In [ ]:
# Question. Find the 5th and 95th percentile of iris's sepallength


# Hint: np.percentile(iris_data, q=[5, 95])

array([4.6  , 7.255])

In [ ]:
# Question: Insert np.nan values at 20 random positions in iris_2d dataset



array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       ...,
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [ ]:
# Question: Find the number and position of missing values in iris_2d's sepallength (1st column)


# Find total mising value in complete data





In [ ]:
# Question: Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0


array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [ ]:
# Question: Select the rows of iris_2d that does not have any nan value.


In [ ]:
#print(np.corrcoef(iris_data[:, 1], iris_data[:, 3])[0,1])

-0.35654408961380535


In [ ]:
np.unique(iris_data, return_counts=True)

(array([0.1, 0.2, 0.3, ..., 7.6, 7.7, 7.9]),
 array([ 6, 28,  7, ...,  1,  4,  1]))

In [ ]:
# Question: Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

# Add the new column and print whole dataset


array([[b'5.1', b'3.5', b'1.4', b'0.2', 38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', 35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', 33.238050274980004]], dtype=object)

In [ ]:
# Question: Find the most frequent value of petal length (3rd column) in iris dataset.



b'1.5'

In [ ]:
# Question: Find the position of the first occurrence of a value greater than 1.0 in
# petalwidth 4th column of iris dataset.


array([50])

In [ ]:
# Question: From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

# Solution


array([27.63, 14.64, 21.8 , 30.  , 10.  , 10.  , 30.  , 30.  , 10.  ,
       29.18, 30.  , 11.25, 10.08, 10.  , 11.77, 30.  , 30.  , 10.  ,
       30.  , 14.43])

In [ ]:
# Question: Get the positions of top 5 maximum values in a given array a.


Positions
Values


array([48.95, 44.67, 42.39, 41.47, 41.  ])

In [ ]:
# Question: Compute the counts of unique values row-wise.



In [ ]:
# Question: Convert array_of_arrays into a flat linear 1d array.


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#Create a padding of zeros (all sides) for the given 5x5 array

[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 1. 1. 0.]
 [0. 1. 1. ... 1. 1. 0.]
 ...
 [0. 1. 1. ... 1. 1. 0.]
 [0. 1. 1. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
#To simply reverse an array of 1 to 50

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]
